[package]
name = "hash_utils"
version.workspace = true
edition.workspace = true

[build-dependencies]
vergen = "7.5.1"

[dependencies]
pyo3 = { workspace = true }
sha2 = { workspace = true }

[lib]
name = "hash_utils"
crate-type = ["cdylib"] 