[package]
name = "test_rust_project"
version = "0.1.0"
edition = "2024"

[dependencies]

[dependencies]
pyo3 = { version = "0.20", features = ["extension-module"] }

[lib]
name = "test_rust_project"
crate-type = ["cdylib"]
