[package]
name = "image_tools"
version.workspace = true
edition.workspace = true

[build-dependencies]
vergen = "7.5.1"

[dependencies]
pyo3 = { workspace = true }
image = { workspace = true }

[lib]
name = "image_tools"
crate-type = ["cdylib"] 